version: '3.5'

services:
  gamfibo:
    image: gamfibo
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      REDIS_URL: "redis://redis:6379"
    env_file:
      - .env
    ports:
      - 3001:3001
    volumes:
      - ./data:/app
    restart: unless-stopped

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"